package at.co.netconsulting.balancesheet.enums

enum class Position(val displayName: String) {
    arbeitssuche("Arbeitssuche"),
    auto("Auto"),
    bank("Bank"),
    betriebskosten_garagenplatz_a1_12("Betriebskosten Garagenplatz A1/12"),
    betriebskosten_garagenplatz_a3_17("Betriebskosten Garagenplatz A3/17"),
    betriebsratsumlage("Betriebsratsumlage"),
    digitale_arbeitsmittel("Digitale Arbeitsmittel"),
    einkommen("Einkommen"),
    essen("Essen"),
    fachliteratur("Fachliteratur"),
    fortbildung("Fortbildung"),
    freizeit("Freizeit"),
    hausverwaltung("Hausverwaltung"),
    homeoffice_pauschale("HomeOffice-Pauschale"),
    internet("Internet"),
    klimaanlage("Klimaanlage"),
    mieteinkommen("Mieteinkommen"),
    obs_haushaltsabgabe("OBS-Haushaltsabgabe"),
    rechts_und_beratungskosten("Rechts -und Beratungskosten"),
    reparaturruecklage_garagenplatz_a1_12("Reparaturrücklage Garagenplatz A1/12"),
    reparaturruecklage_garagenplatz_a3_17("Reparaturrücklage Garagenplatz A3/17"),
    shop("Shop"),
    strom("Strom"),
    steuerberater("Steuerberater"),
    telefon("Telefon"),
    medizin("Medizin"),
    versicherung("Versicherung"),
    vermietung_garage("Vermietung Garage"),
    wasser_heizung("Wasser/Heizung")
}
